#spring.profiles.active: local
server:
  port: 80
  #ssl:
  #  enabled: true # Uses self-signed certificate because no key-store configuration is specified.

internal.lb.uri: http://127.0.0.1
spring:
  cloud:
    gateway:
      routes:
        - id: employee
          uri: ${internal.lb.uri}:9000
          predicates:
            - Path=/api/v1/emp**
          filters:
            - RewritePath=/(?<path>.*), /$\{path}
        - id: supplier
          uri: ${internal.lb.uri}:9001
          predicates:
            - Path=/api/v1/sup**
          filters:
            - RewritePath=/(?<path>.*), /$\{path}
        - id: main-app
          uri: ${internal.lb.uri}:3000
          predicates:
            - Path=/**
          filters:
            - RewritePath=/(?<path>.*), /$\{path}
