server:
  port: 8080

spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: msvc-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: employe
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/emp/**
          filters:
            - RewritePath=/(?<path>.*), /$\{path}
        - id: supplier
          uri: http://localhost:8091
          predicates:
            - Path=/api/v1/sup/**
          filters:
            - RewritePath=/(?<path>.*), /$\{path}

